# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tapi < Formula
  desc "Terminal API Explorer - A beautiful TUI for OpenAPI specs"
  homepage "https://github.com/ksysoev/tapi"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ksysoev/tapi/releases/download/v0.0.1/tapi_Darwin_x86_64.tar.gz"
      sha256 "5b021224f788755640b07213e476303a6e552382ed7a1675f0625242da180b1f"

      def install
        bin.install 'tapi'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ksysoev/tapi/releases/download/v0.0.1/tapi_Darwin_arm64.tar.gz"
      sha256 "fadbbe2735d93242479b63a6518db1d4b7e9c9cde52a6a7cf2105145bb43f5cd"

      def install
        bin.install 'tapi'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ksysoev/tapi/releases/download/v0.0.1/tapi_Linux_x86_64.tar.gz"
      sha256 "3edd32dabea28ecc5298ec5ab426478c0a99cbef868f914bd84d5dc78f4f3e8b"
      def install
        bin.install 'tapi'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ksysoev/tapi/releases/download/v0.0.1/tapi_Linux_arm64.tar.gz"
      sha256 "3db6d8c4df2a0a3f2aecaaec81305fe5960a6b7aba7ab00337dc6dee51c49b42"
      def install
        bin.install 'tapi'
      end
    end
  end

  test do
    system "#{bin}/tapi", "--version"
  end
end
